### PR TITLE
Communicate directly with solr for catalog, dpul, and pulfalight

### PR DESCRIPTION
**Pull request by sandbergja**
Part of #11 

Goals:

- Reduce the load on the catalog application servers
- Eliminate the possibility that a change in one of the rails applications could inadvertently affect the allsearch.  (Note that we could still experience issues if a solr configuration or indexing process is changed).

Outstanding questions:

- What is the best way to set up a dev environment?  Create an SSH tunnel?  Or have a bunch of solr collections running locally in lando?
- Why is the findingaids [blacklight API response](https://github.com/pulibrary/allsearch_rails_api/blob/df921d6d11d5581691e34bd33ab2db92e26cc957/spec/fixtures/files/findingaids/cats.json) so different than the [solr API response](https://github.com/pulibrary/allsearch_rails_api/blob/df921d6d11d5581691e34bd33ab2db92e26cc957/spec/fixtures/files/solr/findingaids/cats.json)?  Which is preferable?
- How do we make a decision between the two approaches?

### CODE REVIEW

**Comment by christinach** [comment]
_What is the best way to set up a dev environment? Create an SSH tunnel? Or have a bunch of solr collections running locally in lando?_: For a dev environment it would be better to use lando and have solr colelctions running locally.

**Comment by maxkadel** [comment]
> - Why is the findingaids [blacklight API response](https://github.com/pulibrary/allsearch_rails_api/blob/df921d6d11d5581691e34bd33ab2db92e26cc957/spec/fixtures/files/findingaids/cats.json) so different than the [solr API response](https://github.com/pulibrary/allsearch_rails_api/blob/df921d6d11d5581691e34bd33ab2db92e26cc957/spec/fixtures/files/solr/findingaids/cats.json)?  Which is preferable?

I don't know exactly why the sort is so different, but my best guess that it has to do with the CatalogController and sort behavior. 

I think it's important that the sort match between the Allsearch and the specific service's default search, because I think otherwise it will be very disorienting for users. This also gives the service application developers more fine-grained control over search result sorting. 

I understand the desire to hit the Solr API directly, for speed and load, but I think specifically re-creating the Solr queries the different Blacklight apps create will be time consuming, and would be very prone to drift. I think there's similar risk for breaking changes between the Blacklight apps and hitting Solr directly.

**Comment by sandbergja** [comment]
> specifically re-creating the Solr queries the different Blacklight apps create will be time consuming

Almost all of the complexity in what Orangelight sends to Solr is related to facets, which we wouldn't need to recreate for this application.  Of the [52 lines in this query, for example](https://github.com/pulibrary/solr_load_testing/blob/main/sample_kw_response.json#L6-L58), only one has to do with the sort order.  And I'd be happy to add a sort param to my PR.

Not sure if this is true of the other applications as well.

**Comment by kevinreiss** [comment]
```
What is the best way to set up a dev environment? Create an SSH tunnel? Or have a bunch of solr collections running locally in lando?
```
Creating four local local collections in solr for all four of these applications seems like a lot to manage and build. For local dev purposes couldn't we just query the staging or qa environments (regardless of using solr or the blacklight api) of these applications when the application is running in dev mode.

**Comment by maxkadel** [comment]
> couldn't we just query the staging or qa environments (regardless of using solr or the blacklight api) of these applications when the application is running in dev mode.

The Solr endpoints are not accessible without tunneling into the machines - you can't go directly to, for existence http://lib-solr8-prod.princeton.edu:8983/solr/catalog-production (the URL Orangelight points to)

**Comment by kevinreiss** [comment]
In terms of arriving at a decision on Blacklight API vs. Solr since we have implemented both talking to the Blacklight API and talking directly to solr can we compare the following points:

1. Response Time
2. Bandwidth saved by not returning data related to facets

**Comment by sandbergja** [comment]
I benchmarked this branch against main using the following shell script:
```
#!/bin/sh
declare -a words=("check" "quaint" "flamingo" "piano" "team" "hiccup" "cherry" "literature" "nomination" "diameter" "layer" "mutter" "tongue" "inspire" "amber" "rugby" "rescue" "width" "brush" "braid")
for word in "${words[@]}"
do
   curl "http://localhost:3000/search/catalog?query=$word"
done
```

On main, this script took 24.649 seconds to run.  On this branch, it took 4.974 seconds (~6x faster).

**Review by christinach — APPROVED** [review]
@sandbergja thank you ! I do believe that avoiding an extra later using the Blacklight API will save us time. You've also benchmarked it and it shows that it is much faster. I'm happy to merge it! Thanks!

**Pull request merged**
